apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-config
  namespace: patient-management
data:
  AUTH_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/auth_db"
  PATIENT_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/patient_db"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_SQL_INIT_MODE: "always"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  BILLING_SERVICE_ADDRESS: "billing-service"
  BILLING_SERVICE_GRPC_PORT: "9001"
  AUTH_SERVICE_URL: "http://auth-service:4005"
