apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pm-ingress
  namespace: patient-management
spec:
  rules:
    - host: patient-management.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4004
