### POST request to create Patient
POST http://127.0.0.1:2487/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Shivani Sharma",
  "email": "LoveUshivani@gmail.com",
  "address":"Magarpatta,Pune",
  "dateOfBirth": "2002-12-20",
  "gender": "Female",
  "registeredDate": "2026-03-22"
}
###