apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: avinash190420/pm-analytics-service
          ports:
            - containerPort: 4002
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: pm-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
