apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: avinash190420/pm-api-gateway
          ports:
            - containerPort: 4004
          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: pm-config
                  key: AUTH_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
