apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: patient-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: avinash190420/pm-billing-service
          ports:
            - containerPort: 4001
            - containerPort: 9001
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
